export enum WorkingHoursEnum {
    USERNAME_ALIAS = 'Working Hours Bot',
    EMOJI_AVATAR = ':hourglass_flowing_sand:',
    DEFAULT_TITLE = 'Working Hours',
    USE_WORKING_HOURS = 'Use working hours?',
    USE_WORKING_HOURS_ACTION_ID = 'useWorkingHours',
    VIEW_ID = 'workingHours',
    DAYS_LABEL = 'Select working days',
    DAYS_ACTION_ID = 'days',
    FROM = 'From time',
    FROM_ACTION_ID = 'from',
    TO = 'To time',
    TO_ACTION_ID = 'to',
    ADD_TIME = 'Add',
    ADD_TIME_ACTION_ID = 'add-time',
    SEND_MESSAGE_ACTION_ID = 'send-message',
    SEND_MESSAGE = 'Yes, send my message',
    MESSAGE_PREVENTED = 'This person is not in his/her working hours. Would you like to send this message anyway?',
    CANCEL_JOB = 'cancel-job',
    TIMEOUT_MINUTES = '3',
    TIMEOUT = '3 minutes',
    TIMEOUT_MESSAGE = ':+1: we won\'t ask you again for the next 3 minutes',
}
